import type { IconType } from "react-icons";
import {
  SiGo,
  SiPython,
  SiTypescript,
  SiJavascript,
  SiGnubash,
  SiReact,
  SiNextdotjs,
  SiAngular,
  SiHtml5,
  SiCss,
  SiSass,
  SiTailwindcss,
  SiGin,
  SiNodedotjs,
  SiFlask,
  SiNestjs,
  SiGraphql,
  SiSocketdotio,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiGithubactions,
  SiJenkins,
  SiNginx,
  SiFirebase,
  SiLinux,
  SiGit,
} from "react-icons/si";

/** Simple Icons components keyed by the `icon` names used in content/skills.json. */
export const skillIconMap: Record<string, IconType> = {
  SiGo,
  SiPython,
  SiTypescript,
  SiJavascript,
  SiGnubash,
  SiReact,
  SiNextdotjs,
  SiAngular,
  SiHtml5,
  SiCss,
  SiSass,
  SiTailwindcss,
  SiGin,
  SiNodedotjs,
  SiFlask,
  SiNestjs,
  SiGraphql,
  SiSocketdotio,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiGithubactions,
  SiJenkins,
  SiNginx,
  SiFirebase,
  SiLinux,
  SiGit,
};
